@startuml
skinparam Style StrictUML
skinparam Linetype ortho 



entity "Patient" as patient {
    *Patient_id: varchar <<PK>>
    --
    *First_name: varchar(50)
    Middle_name: varchar(50)
    *Surname: varchar(50)
    *Address: varchar(200) <<Multivalued>>
    *Phone_num: varchar(25) <<Multivalued>>
    *Gender: varchar(50)
    *DOB: date
    *AGE<18: boolean <<Derived>>
    Email: varchar(320)
    Health_cond: varchar(100)
    Allergies: varchar(100)
}

entity "Staff" as staff {
    *Staff_id: varchar <<PK>>
    --
    *First_name: varchar(50)
    Middle_name: varchar(50)
    *Surname: varchar(50)
    *Address: varchar(200) <<Multivalued>>
    *Phone_num: varchar(25) <<Multivalued>>
    *Position: varchar(100)
    *Dateofemployment: date
    *IRDnum: char(9)
    ' IRDnum is either 8 or 9 digits however, if its 8 an 0 is added at the front making it a 9 digit number
    *Email: varchar(320)

}

entity "Booking" as booking {
    *Booking_id: varchar <<PK>>
    --
    *Patient_id: varchar <<FK>>
    *Staff_id: varchar <<FK>>
    *Timedate: datetime
    *Procedure_id: varchar <<FK>>
    *Location: varchar(200)
    Notes: varchar(500)
}

entity "Procedure" as procedure {
    *Procedure_id: varchar <<PK>>
    --
    *Description: varchar(500)
    *Quantity: integer
    *Timedate: datetime
    ' timedate to roughly know how long each procedure takes
    *Cost: deciaml(10,2)
    *Gst: float
    Grams: integer
}

entity "Booking_procedures" as booking_procedures{
    *Booking_id: varchar <<FK>>
    *Procedure_id: varchar <<FK>>
    --
}

entity "Schedule" as schedule {
    *Booking_id: varchar <<FK>>
    *Timedate: datetime
    --
    Notes: varchar(200)
    *Bookings: varchar(100)
}

entity "Payments" as payments {
    *Booking_id: varchar <<FK>>
    *Patient_id: varchar <<FK>>
    --
    *Total_cost: float
    *Daysinceoperation: integer
    *Pay boolean: boolean
}


patient ||-|{ booking
staff ||--|{ booking : each booking can have 1 or 2 staff
booking ||-|{ booking_procedures
procedure ||--|{ booking_procedures
schedule ||-o{ booking
staff ||-|| schedule
booking ||--|{payments
patient ||-|{ payments
@enduml